services:
  storage:
    image: minio/minio:latest
    command: minio server /var/lib/minio/data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=ppteam3
      - MINIO_ROOT_PASSWORD=@PPTeam123!
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/var/lib/minio/data
    networks:
      - go_networks
volumes:
  storage:
networks:
  go_networks: